---
components:
  - type: LDR20
    parent_link: mount_link
    xyz: -0.19 0.0 0.0
    rpy: 0.0 0.0 0.0

  - type: WCH01
    parent_link: front_bumper_link
    xyz: -0.01 0.0 0.0
    rpy: 0.0 0.0 0.0
