x-common-config:
  &common-config
  network_mode: host
  ipc: host

services:
  docking:
    image: husarion/husarion-ugv-autonomy:humble-ros2-dock-suggestions
    container_name: docking
    <<: *common-config
    volumes:
      - ..:/ros2_ws/src/husarion_ugv_autonomy_ros
      - ./config:/config
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONE_DDS_URI=file:///config/cyclonedds.xml
    command: >
      ros2 launch husarion_ugv_docking docking.launch.py
        namespace:=panther
        use_wibotic_info:=True
        camera_image_topic:=${CAMERA_IMAGE_TOPIC:-/panther/camera/color/image_raw}
        camera_info_topic:=${CAMERA_INFO_TOPIC:-/panther/camera/color/camera_info}
        docking_server_config_path:=/config/docking_server.yaml
        apriltag_config_path:=/config/apriltag.yaml
        apriltag_size:=0.08
        use_sim:=True

  navigation:
    image: husarion/husarion-ugv-autonomy:humble-ros2-dock-suggestions
    container_name: navigation
    <<: *common-config
    volumes:
      - ..:/ros2_ws/src/husarion_ugv_autonomy_ros
      - ../maps:/maps
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    command: >
      ros2 launch husarion_ugv_navigation bringup_launch.py
        namespace:=panther
        observation_topic:=${OBSERVATION_TOPIC:-err}
        observation_topic_type:=${OBSERVATION_TOPIC_TYPE:-err}
        slam:=${SLAM:-True}
        use_sim_time:=False
